### ISSUE TITLE
Add github repo/credits as footer

### ISSUE THREAD

**Issue by rickr** [OperationCode/vettec#4]
Lets add a little, very subtle footer to let people know: 
* This page was created by deploy (with a link)
* It's opensource and contributions are welcome (with a link to this repo)

**Comment by hollomancer** [comment]
@Wimsy113, do we have the footer image for Deploy?

**Comment by Wimsy113** [comment]
sure do!

![deploy_logo_revamp](https://cloud.githubusercontent.com/assets/7386887/24872912/10b7ead6-1ded-11e7-921e-1149c9fdd980.png)

**Comment by rickr** [comment]
Fixed in #21
