### ISSUE TITLE
Add 'Supporters' section

### ISSUE THREAD

**Issue by rickr** [OperationCode/vettec#6]
At the bottom of the page add a new 'Supporters' section with logos of people supporting this bill and their logos, with a link to their home page.

First two: 
- [ ] Operation Code (use the logo with text)
- [x] PDX Code Guild (logo attached)
![PDX Code Guild](https://cloud.githubusercontent.com/assets/334550/24768162/ce49c2a4-1abe-11e7-9309-4aa9ed1f90dc.png)

**Comment by hollomancer** [comment]
Add Aerobatic

@davidmolina, let's reach out to Microsoft/Udacity

**Comment by davidmolina** [comment]
Roger.
